name: densities4risk
channels:
  - defaults
  - conda-forge
dependencies:
  - aom=3.6.0=hd77b12b_0
  - arrow-cpp=21.0.0=h0399227_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.3.0=py313haa95532_0
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - bottleneck=1.4.2=py313h2cb717b_0
  - brotlicffi=1.0.9.2=py313h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py313h02ab6af_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py313h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.17=py313h927ade5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=py313haa95532_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py313h02ab6af_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py313haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=7.0.1=pyh6dadd2b_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.0=py313haa95532_0
  - jsonschema-specifications=2023.7.1=py313haa95532_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - kiwisolver=1.4.8=py313h5da7b33_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.1.1=h827c3e9_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.15.0=h2300eb9_0
  - libdeflate=1.22=h2466b09_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libgrpc=1.71.0=hf4237ab_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libmpdec=4.0.0=h827c3e9_0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_4
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.3=py313hd650c13_0
  - matplotlib=3.10.6=py313haa95532_0
  - matplotlib-base=3.10.6=py313h26e45b9_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=1.3.11=py313h5810407_1
  - mkl_random=1.2.8=py313hedd7022_1
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - narwhals=2.7.0=py313haa95532_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hc388f54_1
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbconvert-pandoc=7.16.6=h7d6f222_1
  - nbformat=5.10.4=py313haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.11.0=py313h7660c64_1
  - numpy=2.3.3=py313h050da96_1
  - numpy-base=2.3.3=py313h1e017a8_1
  - openjpeg=2.5.2=h9b5d1b5_1
  - openpyxl=3.1.5=py313h827c3e9_1
  - openssl=3.6.0=h725018a_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h42c1672_0
  - pandoc=3.8.3=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=py313haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py313hb328d1f_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.3.0=py313h4442805_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.1=py313h5ea7bf4_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py313h42c1672_0
  - pycparser=2.23=py313haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.0=py313haa95532_0
  - pyqt=6.9.1=py313h12ec796_0
  - pyqt6-sip=13.10.2=py313h630b2a1_0
  - pysocks=1.7.1=py313haa95532_0
  - python=3.13.7=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-fastjsonschema=2.20.0=py313haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313haa95532_0
  - pywavelets=1.9.0=py313h02ab6af_0
  - pywin32=311=py313h40c08fc_1
  - pyzmq=27.1.0=py313h7149c55_0
  - qtbase=6.9.2=hd965823_2
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - re2=2024.07.02=h214f63a_0
  - referencing=0.30.2=py313haa95532_0
  - requests=2.32.5=py313haa95532_0
  - rpds-py=0.22.3=py313h636fa0f_0
  - scipy=1.16.2=py313hbd6d557_0
  - seaborn=0.13.2=py313haa95532_3
  - setuptools=80.9.0=py313haa95532_0
  - sip=6.12.0=py313h706e071_0
  - six=1.17.0=py313haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py313h2cb717b_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py313h5ea7bf4_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py313haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - choreographer==1.2.0
      - iniconfig==2.3.0
      - kaleido==1.1.0
      - logistro==2.0.0
      - orjson==3.11.3
      - pluggy==1.6.0
      - pytest==8.4.2
      - pytest-timeout==2.4.0
      - simplejson==3.20.2
prefix: C:\Users\user\anaconda3\envs\densities4risk
